### PR TITLE
ENH: Error message pop-up 

### PR DESCRIPTION
**Pull request by YektaY**
## Description
This PR makes a base BadgerError class and then adds a popup that contains a message for the user. It also changes the name of BadgerRunTerminatedError exception to BadgerRunTerminated

### CODE REVIEW

**Comment by YektaY** [comment]
ok, this ready for review. I would definitely try it out and let me know if you want any other changes or features.

**Comment by roussel-ryan** [comment]
Looks mostly good, but the detailed traceback is not being shown
image

**Comment by YektaY** [comment]
Ok, I have added the traceback of the exception or the call stack - it looks like a lot of the issues are raised outside of a try except block, so the popup occurs before the exception so instead it displays the call stack.

**Comment by roussel-ryan** [comment]
Yep that works, can we wrap the following code in a BadgerRuntime Error or similar such that the errorbox pops up 
File "/home/rroussel/Badger/src/badger/core_subprocess.py", line 229, in run_routine_subprocess
    raise e

**Review by roussel-ryan — APPROVED** [review]

**Pull request merged**
